# Generated by Django 4.1.3 on 2022-12-05 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("keywords", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                ("price", models.FloatField()),
                ("amouth", models.IntegerField()),
                ("detail", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Evet"), ("False", "Hayır")], max_length=10
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.TimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.category"
                    ),
                ),
            ],
        ),
    ]
