# Generated by Django 4.1.4 on 2022-12-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContackFormMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20)),
                ("email", models.CharField(blank=True, max_length=50)),
                ("subject", models.CharField(blank=True, max_length=50)),
                ("message", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Evet"), ("False", "Hayır")],
                        default="New",
                        max_length=10,
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=20)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("phoneNumber", models.CharField(blank=True, max_length=11)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
