# Generated by Django 4.1.4 on 2022-12-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("keywords", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("adress", models.CharField(max_length=190)),
                ("icon", models.ImageField(blank=True, upload_to="images/")),
                ("phone", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=130)),
                ("company", models.CharField(max_length=50)),
            ],
        ),
    ]
